"""
Django settings for power_analyzer project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'duq11xty6yn=y&dp7%xcv7f*5b+8^kvp$96ug6)4j@myfu18(l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECURITY WARNING: EMAIL USERNAME AND PASSWD
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sparkpostmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "SMTP_Injection"
EMAIL_HOST_PASSWORD = "d8dc6379b6aad714b9b55f1ada896e572a4f80d7"
EMAIL_SUBJECT_PREFIX = "Power Analyzer"
DEFAULT_FROM_EMAIL = "Power Analyzer <no-reply@power.rabello.info>"

ALLOWED_HOSTS = [
    "172.16.38.103",
    "127.0.0.1",
    "localhost",
    "blarple.net",
    "35.165.91.189",
    "pa.rabello.info",
]

SERVER_URL = "https://pa.rabello.info"

CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    'datapoints.apps.DatapointsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'power_analyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'power_analyzer.wsgi.application'

STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/admin/static/'

# Custom settings
ARCHIVE_TIME = 30       # Archive interval in minutes

# This is (m, b) in the queation I = m * V + b for the current transformer.
CT_CURRENT = {
    "10A": (10.29, 6.9635)
}

# This is the linear quation for going from the ADC value to the voltage
CT_VOLTAGE = {
    "10A": (0.003, 0.0097)
}

#Vin = [(V_adc/num_bits)*max_val-offset]/scale_factor
V_IN = {
    "num_bits": 1024,
    "max_val": 3.1,
    "offset": 1.5,
    "scale_factor": complex(0.0040, 0.0045),
}

#Iin = {[(V_adc/num_bits)*max_val-offset]/scale_factor}/resistance*secondary
I_IN = {
    "num_bits": 1024,
    "max_val": 3.1,
    "offset": 1.5,
    "scale_factor": 454.45E-3,
    "resistance": 42,
    "secondary": .2,
}

MEASUREMENT_FIELDS = [
    "phase",
    "magnitude",
    "v_magnitude",
    "v_phase",
    "i_magnitude",
    "i_phase",
]
