# Generated by Django 2.0 on 2018-02-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0003_auto_20180209_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='current',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='phase',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='power',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='voltage',
            field=models.FloatField(null=True),
        ),
    ]
