# Generated by Django 2.0 on 2018-03-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0003_auto_20180303_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='phase_offset',
            field=models.CharField(choices=[('left', 'Left 0 degrees'), ('right', 'Right +180 degrees')], default='right', max_length=30),
        ),
    ]
