# Generated by Django 2.0 on 2018-05-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0004_auto_20180307_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='current',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='power',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='voltage',
        ),
        migrations.RemoveField(
            model_name='unarchivedmeasurement',
            name='current',
        ),
        migrations.RemoveField(
            model_name='unarchivedmeasurement',
            name='power',
        ),
        migrations.RemoveField(
            model_name='unarchivedmeasurement',
            name='voltage',
        ),
        migrations.AddField(
            model_name='measurement',
            name='magnitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='max_phase',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unarchivedmeasurement',
            name='magnitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='phase',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unarchivedmeasurement',
            name='phase',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
