# Generated by Django 2.0 on 2018-05-31 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0005_auto_20180530_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField()),
                ('frequency_limit', models.IntegerField()),
                ('max_val', models.FloatField(null=True)),
                ('min_val', models.FloatField(null=True)),
                ('email', models.CharField(max_length=200)),
                ('attribute', models.CharField(choices=[('phase', 'Phase'), ('magnitude', 'Magnitude')], default='magnitude', max_length=200)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapoints.Circuit')),
            ],
        ),
    ]
