# Generated by Django 2.0 on 2018-06-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0005_auto_20180530_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='max_phase',
            new_name='max_p_phase',
        ),
        migrations.AddField(
            model_name='measurement',
            name='i_magnitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='i_phase',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='max_i',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='v_magnitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='v_phase',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unarchivedmeasurement',
            name='i_magnitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unarchivedmeasurement',
            name='i_phase',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unarchivedmeasurement',
            name='v_magnitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unarchivedmeasurement',
            name='v_phase',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
