# Generated by Django 2.0 on 2018-06-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0006_auto_20180601_1929'),
        ('datapoints', '0006_alert'),
    ]

    operations = [
    ]
