# Generated by Django 2.0 on 2018-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0007_merge_20180601_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='attribute',
            field=models.CharField(default='magnitude', max_length=200),
        ),
    ]
