# Generated by Django 2.0 on 2018-06-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0008_auto_20180604_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='ct_windings',
            field=models.IntegerField(default=2000),
        ),
    ]
